version: "3"

services:
  reddit-api:
    build: ./redditAPI
    volumes:
      - ./redditAPI:/app
    ports:
      - 3100:3100
  video:
    build:
      context: ./Video
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: video