version: "3"

services:
  reddit-api:
    build: ./redditAPI
    volumes:
      - ./redditAPI:/app
    ports:
      - 3100:3100
    env_file:
      - ./redditAPI/.env
  video:
    build:
      context: ./Video
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: video
    env_file:
      - ./Video/.env
    privileged: true
  youtube:
    build: ./youtube
    volumes:
      - ./youtube:/app
    ports:
      - 5000:5000
    env_file:
      - ./youtube/.env
